### ISSUE TITLE
Installation of GitHub Package on Win 10 64-bit

### ISSUE THREAD

**Issue by AbdullahSallam** [bedatadriven/activityinfo-R#1]
When I try to install GitHub package with the command:

install_github( "bedatadriven/activityinfo-R", ref = "release")", 

the installation fails with following message:
----
Downloading GitHub repo bedatadriven/activityinfo-R@release
from URL https://api.github.com/repos/bedatadriven/activityinfo-R/zipball/release
Installing activityinfo
"C:/PROGRA~1/R/R-32~1.3/bin/x64/R" --no-site-file --no-environ --no-save  \
  --no-restore --quiet CMD INSTALL  \
  "C:/Users/Lara/AppData/Local/Temp/RtmpARBQ3n/devtools5301bc13101/bedatadriven-activityinfo-R-a7898de"  \
  --library="C:/OneDrive/المستندات/R/win-library/3.2" --install-tests 

* installing *source* package 'activityinfo' ...
Warning in file(file, ifelse(append, "a", "w")) :
  cannot open file 'C:/OneDrive/GacSJdOGJ/R/win-library/3.2/activityinfo/DESCRIPTION': No such file or directory
Error in file(file, ifelse(append, "a", "w")) : 
  cannot open the connection
ERROR: installing package DESCRIPTION failed for package 'activityinfo'
* removing 'C:/OneDrive/المستندات/R/win-library/3.2/activityinfo'
Error: Command failed (1)

**Comment by mjkallen** [comment]
Looks like you may not have permission to make changes to `C:/OneDrive/المستندات/R/win-library/3.2`, therefore this is unrelated to the *activityinfo* R package.

You can consult the *R for Windows FAQ* and especially [I don’t have permission to write to the R-3.3.0\library directory](https://cran.r-project.org/bin/windows/base/rw-FAQ.html#I-don_0027t-have-permission-to-write-to-the-R_002d3_002e3_002e0_005clibrary-directory) to see if you can resolve this issue.
