### ISSUE TITLE
Allow users to specify a custom record ID when using addRecord()

### ISSUE THREAD

**Issue by jamiewhths** [bedatadriven/activityinfo-R#111]
From [AI-3942](https://bedatadriven.atlassian.net/browse/AI-3942)
Resolved by commit: [2b4bcf6](https://github.com/bedatadriven/activityinfo-R/commit/2b4bcf60c1f0d29d0d922cffe6e4f4e88f4d5a66)

**Comment by nickdickinson** [comment]
Noting that this implementation uses the getRecord API call to check if the recordId already exists. If tables are wide, I imagine it may be significantly more efficient to do a table query for the id column with a limit of 1 instead? This could be tested in the future. If that is desirable I can add an issue to the backlog.

**Comment by akbertram** [comment]
@nickdickinson Because of the way we implement queries, `getRecord()` will always be faster.
