### ISSUE TITLE
Rationalize GitHub checks

### ISSUE THREAD

**Issue by akbertram** [bedatadriven/activityinfo-R#116]
We have one passing check, and the others are systematically failing.
Can we consolidate? 
Do we need cross platform testing?
At least get everything passing reliably.

**Comment by nickdickinson** [comment]
Everything is defined in the GHA workflow `R-CMD-check`. Tests are run using windows-latest and ubuntu-latest. I tested separately on MacOS and could not find why the GHA didn't work on MacOS so leaving out. If we find it is required, I can test further for other GHA that could be used for MacOS. I think we'll cover most edge cases with two OSs.

Note, it is also possible to manually trigger a test in a rocker container, which skips the longer `R-CMD-check`. This is the GHA called `activityinfo-R-package-tests`
