### ISSUE TITLE
functionality that can inform user that there is an error in calculated fields (or any other kind of error)?

### ISSUE THREAD

**Issue by Ryo-N7** [bedatadriven/activityinfo-R#18]
Is there something in the API that would let you know if a formula in a calculated field has an error?

In the ActivityInfo interface, you can clearly see that when you are viewing a form but I don't see anyway that from a bird's-eye-view, lets you see across all of the tables within a single database where there is some error in calculated fields (or any other errors within tables in general, not just formulas in calculated fields). Unless I missed something?

Maybe this isn't possible via ActivityInfo's API but it would be interesting because for example I can create a script that can check for these errors and if there are, send an email to the project MIS person and/or me to point out which fields in which table are "erroring" and to prompt them to take a look.

**Comment by mjkallen** [comment]
Hi there, you should send these kinds of questions to our support desk if you need a prompt reply. These repositories are not continuously monitored for comments and questions.

To answer your question: no, there is no such thing in the API and I don't think that this is something you would ever support.
