### ISSUE TITLE
Add test suite to prevent regressions

### ISSUE THREAD

**Issue by akbertram** [bedatadriven/activityinfo-R#21]
We currently lack a test suite for this package A test suite would help prevent regressions caused by changes to the R package, but also ensure that changes to the ActivityInfo server does not break the R package.

We should model the test suite after ActivityInfo's existing Java API Test library that uses the following approach:
1. Every test creates a new user in the pre-preproduction environment with a completely blank slate
2. Each test sets up any required fixtures like a database, forms, etc.
3. Verify results using the temporary database.

This means that running tests require access to ActivityInfo's pre-production environment; this can be provided to any contributor who requires it.

**Comment by nickdickinson** [comment]
Added in 4.30
