### ISSUE TITLE
Favor API token authentication

### ISSUE THREAD

**Issue by akbertram** [bedatadriven/activityinfo-R#22]
We currently have an `activityInfoLogin()` function which accepts a username and password to authenticate to the API. However, we are deprecating this approach and now offer [personal api tokens](https://www.activityinfo.org/support/docs/m/84880/l/1333305.html) as a more secure alternative.

We should:
- [x] Add a new activityInfoToken() method to accept and store the user's api token (User name not required)
- [x] Add a warning message to activityInfoLogin() encouraging users to switch
- [x] Update documentation to highlight activityInfoToken() as the preferred manner of authenticating

**Comment by nawaaugustine** [comment]
Hi Alex, do you have any estimated time to complete this feature?

**Comment by akbertram** [comment]
Hi Nawa, this is mostly related to documentation. You can use a personal api token in place of a password in the current version.

**Comment by nickdickinson** [comment]
Closing it out. Addressed in 4.30.
