### ISSUE TITLE
RMarkdown chunks issue

### ISSUE THREAD

**Issue by Ryo-N7** [bedatadriven/activityinfo-R#29]
Despite setting `message=FALSE`, ActivityInfo API messages still appear in the knitted RMD document. It also breaks up a single chunk into separate ones for each ActivityInfo API call for some reason, which creates separate 'Share Code' buttons below. I need to set it to `include=FALSE` for the messages to disappear entirely, but that then means I can't share the code in the document.

![rmd-activityinfo-chunk](https://user-images.githubusercontent.com/19657164/203939867-e58c7964-01f7-4644-9358-f3126ff0a57c.PNG)
![rmd-activityinfo-chunk-RMD](https://user-images.githubusercontent.com/19657164/203939873-e5568c6b-9be7-4d50-a778-4c827138ef3c.PNG)

**Comment by nickdickinson** [comment]
Addressed by removing rogue cat() calls.
