### ISSUE TITLE
Improve documentation and examples in package and/or on website

### ISSUE THREAD

**Issue by Ryo-N7** [bedatadriven/activityinfo-R#35]
Create {pkgdown} website for documentation and vignettes (currently lying dormant in `inst/examples` folder in the Github repository)?

Some of functions also require preparation in the ActivityInfo UI beforehand (setting up forms, roles, formulas, etc.) so it would be nice if documentation could also include stuff like that.

Ex. The various `permissions`/`updateRole` functions took a long time for Robert and I to properly grok as the set-up includes lots of actions needed in ActivityInfo UI in tandem with what's needed in the R code to run, which is a lot of lists-within-lists for filters, parameters, etc. This is a topic that would be perfect for a vignette hosted on a pkgdown website with screenshots of the actual tables and database settings in the ActivityInfo UI alongside the R code.

**Comment by Ryo-N7** [comment]
add package version `release tags` on github

currently it only goes up to 4.20

**Comment by Ryo-N7** [comment]
documentation for internal functions: `stageImport()` and `executeJob()`

for heavy-duty scripts/operations some "power users" may want to use these functions more regularly

they can be kept as 'internal' functions as I imagine most users won't need it but would be nice if they were documented + vignette/example 

-----
also if there was a way to access a log of jobs based on user account that would help too

**Comment by Ryo-N7** [comment]
permissions // roles

examples:
1. multi-partner database (like in https://www.activityinfo.org/support/docs/m/92353/l/1165339.html)
2. set permissions for users with more than one supervisor (reference form would be a list of all db users (one user = one row) with separate column for each supervisor, if any)
3. multiple filters for a user: partner filter AND firm/organization filter

etc...

**Comment by akbertram** [comment]
We are expanding the R package documentation website as part of a larger project to improve AI documentation. You can preview some of the changes here:
https://docs-dot-site-dot-activityinfoeu.appspot.com/support/docs/R/tutorials/introduction-to-activityinfo-api.html

This site will include vignettes as well:
https://docs-dot-site-dot-activityinfoeu.appspot.com/support/docs/R/how-tos/analyze-and-visualize-activityinfo-data.html

I will rewrite the example scripts as proper vignettes.

**Comment by akbertram** [comment]
- [ ] Documentation for all schema field helper functions
- [ ] Vignette tutorial for adding a form and database
- [ ] Update getting started tutorial

**Comment by Ryo-N7** [comment]
**this is a more general point re: documentation**: the documentation should try to further explain ActivityInfo API concepts. like in the field schema docs, in `Arguments` it talks about `presentation: Default is "automatic"`. but it doesn't give me any info on what `presentation` is. I'm sure this is all stuff that's just copy-pasted from the API docs but a bit more elaboration would help users.


also the main package 'references' is a bit messy right now (probably because we've combined all of the form schema functions into one place?)

![asdfasdfasdf](https://user-images.githubusercontent.com/19657164/217477207-dcb77b3c-2ca5-48f0-a2e4-8fadcaa3199e.PNG)

**Comment by akbertram** [comment]
Published here: https://www.activityinfo.org/support/docs/R/index.html
