### ISSUE TITLE
Authenticate without asking user if they would like to save the credentials file

### ISSUE THREAD

**Issue by nickdickinson** [bedatadriven/activityinfo-R#40]
Following PR #27, the request is to offer a way to avoid the request to save the file while in interactive mode.

**Comment by nickdickinson** [comment]
In the next release, there is a global option that is a temporary workaround and allows one to avoid the interactive prompts to save the file: 
`options(activityinfo.interactive = TRUE)`

If you only want this set temporarily in a session that cleans up after the code is finished or an error occurs:
```
library(withr)
withr::with_options(list(activityinfo.interactive = TRUE), {
# Your ActivityInfo r code here
})
```

Eventually we would like an argument saveCredentials that if it is set to TRUE then it would save the credentials to a file and if FALSE it would not, otherwise if missing it would default to the normal interactive approach that current users know.

**Comment by MatayoBweta** [comment]
We should consider this functionality as ready?

**Comment by nickdickinson** [comment]
Yes, if you install the latest version from Github then it should work.

**Comment by akbertram** [comment]
@nickdickinson we can close this right?
