### ISSUE TITLE
Tidy-compatible record fetching

### ISSUE THREAD

**Issue by Ryo-N7** [bedatadriven/activityinfo-R#48]
I get requests to grab table from multiple tables and/or multiple project databases at once. Basically stuff that would be really tedious to do manually (dragging-dropping all the specific columns in the UI, switching between tables and projects, grabbing the correct reference fields, etc.).

So I have my colleagues send me a CSV/Excel of what projects, tables, and fields are needed as columns. See example below (I left-joined together the database ID and form IDs with R separately):

![this](https://user-images.githubusercontent.com/19657164/208458459-060db5f6-855e-4cb5-9e7e-3b19b32fc0ce.PNG)

So basically I want to programmatically iterate over each row so that I'm grabbing the specific fields for a specific table in a specific project, then the next, then the next, etc.

So I created a function to grab the columns I need, transform it into the 'named list' structure needed for the `columns` argument in `queryTable()`:

![farmjobs-query-fields](https://user-images.githubusercontent.com/19657164/208458806-c695368f-b1d8-40e1-8874-f4103da28ad8.PNG)

but I get this back:

![farmjobs-query-res](https://user-images.githubusercontent.com/19657164/208458846-e40a196a-63a8-40c4-b37a-4e2c32fb1a86.PNG)

Only the `Survey.Date` field is returned with proper data because that's the only field that is native to the form I'm querying. 

So looking at this, it means that I have to deliberately go search inside each form-schema and find the correct field ID which adds another layer of complexity and makes something like this where I'm simply trying to grab data from a given set of "field names" and "table IDs" a lot harder than it should be.

What I'm given:
![whatimgiven](https://user-images.githubusercontent.com/19657164/208459188-8af0fb8b-da8f-4ece-a983-d7b39af75bd4.PNG)

What I actually need, which would require even more steps instead of being able to simply match by field name.

![whatiactuallyneed](https://user-images.githubusercontent.com/19657164/208459327-e3403555-dd58-488e-83a4-0e6cda31e2a9.PNG)

The User Interface 'export via R' option gives me the proper field codes as shown above but I can't extract that via R. 

In reality, I can't even find the above "cb1ee1b8.c288fa67" in this form's schema as it only shows me "cb1ee1b8" for the `fieldId`. Which means I'll have to again, jump another level to search the parent form and look up the field using only the field label and grab the field ID of the referenced field.

![howamisupposetofindthis](https://user-images.githubusercontent.com/19657164/208459679-9928ed8d-013c-4af9-a151-43cbbec10a71.PNG)

I shouldn't need any more than this the first screenshot in this email to grab the fields I need from multiple tables in multiple projects but as I explained above its not enough and that's a huge bottleneck for me. I can't ask my colleague to provide me with the reference form IDs and reference field ID because at that point they might as well just manually download all of the forms themselves using the user interface.

So what should be a simple loop over queryTable()​ per 'table_id' selecting columns in 'Field.Names' turns into a complicated process of jumping through 2 different form schemas (the child form schema and then the parent form schema, matching the field by label) then selecting using that (or so I imagine the process would go).

Is there no way to make this process easier?

Or, as I imagine this won't be a simple fix, if we could instead fix the issue with large forms with many reference fields getting status 500 errors when trying to extract them from the API with `queryTable()`, then I can just grab everything (queryTable() with no 'columns' argument) and dplyr::select() afterwards instead.

**Comment by akbertram** [comment]
queryTable() should have the option to provide the same projection of the form as the user interface.

**Comment by akbertram** [comment]
Another option would be to provide a DSL in R to make it easier to write these kinds of queries for custom projections. For example:

```

referenceWithKeyFields <- function(fieldLabel) {
  function(schema) {
    i <- which(sapply(schema$elements,function(e) e$label) == fieldLabel)
    field <- schema$elements[[i]]
    referencedFormId <- field$typeParameters$range
    referencedSchema <- getFormSchema(referencedFormId)
    keys <- which(sapply(schema$elements,function(e) e$label) == fieldLabel)
    // TODO
  }
}

queryTable("cffcflkl1opdbtk2", columns = byLabel("Annual income"), referenceWithKeyFields("Territory"), referenceWithAllFields("Municipality"), referenceWithId("Territory"))
```

**Comment by akbertram** [comment]
Short term fix: See #58 
Discussion to be continued.

**Comment by akbertram** [comment]
Notes from our discussion: @Ryo-N7 @nickdickinson 

getRecords()

# Which columns?

## Everything, with knobs/options

# How to handle references?
referencedIds = TRUE/FALSE
referencedKeys = TRUE/FALSE

## Naming of columns
columnNames = c("labels", # same as in table view
                "codes" # use field codes, fall back to labels if code is missing?
                "ids")  # use field ids
             

checkNames = TRUE/FALSE # should the result of above be mangled to be correct R
syntax 
enforceUnique = TRUE/FALSE

# Same as UI:
allFields(referencedIds = FALSE, referencedKeys = TRUE, naming = "labels")

ui() # Maybe everything from the UI + record ids 

## Only fields/columns I ask for...

columns = c(a = "_id", b = "province", c = "province.name")

## GeoPoints

1- make interaction with sf or other packages straightforward
2- easy to write the data frame to csv with lat/lng

another knob that can control the format

## attachments: later? only as tibble/vector?

# Which records?

Filter argument in queryTable(), but difficult to write activityinfo formula
mixed with R code

for(province in c("Nord Kivu", "Sud Kivu")) {

## Ability to specify formulas using R syntax and (some) R functions.
## Need a way to distinguish between symbols that refer to ActivityInfo form
## fields and symbols in the current environment.
getRecords(formId, filter = province == !province)
}
#quosure


select(df, Province %in% p)

**Comment by Ryo-N7** [comment]
quick thought:

wondering if we should rename `getRecord()` to `getSingleRecord()` as the new version of `queryTable()` becoming `getRecords()` makes them very similar and auto-complete will be annoying?

**Comment by nickdickinson** [comment]
That makes sense but if we also implement an attachment vector for the attachment columns, will we need the getRecord() call?

I guess you would have to deprecate getRecord and favor getSingleRecord so that it doesn't immediately break existing scripts.

**Comment by Ryo-N7** [comment]
i mean people could potentially be using `getRecord()` for reasons beside the attachment use-case

**Comment by Ryo-N7** [comment]
i tried the latest `v4.33`, can't seem to select the proper columns like you've shown above with the dplyr verbs

![getrecords-test](https://user-images.githubusercontent.com/19657164/224347588-6e68ed55-1e41-4f99-939e-d9f59ecb10b8.PNG)

```
projsch <- getFormTree(formId = "c8301e4022c")

# getRecords(form = "c8301e4022c") # form ID or form schema or form tree >> form ID NOT work right now

projtab <- getRecords(form = projsch) %>% select(contains("Activ")) %>% collect()
projtab <- getRecords(form = projsch) %>% select(contains("Activity")) %>% collect()
```

**Comment by Ryo-N7** [comment]
on the other rhand, the `set UI col names` things appears to be working, which is nice!

![grab-by-ui-cols](https://user-images.githubusercontent.com/19657164/224350988-7f6576e6-847f-4bd3-b5e8-08c6c4142752.PNG)

**Comment by nickdickinson** [comment]
Implement filter() and arrange() and send to @Ryo-N7 for testing later this week.

**Comment by nickdickinson** [comment]
Also add tests

**Comment by Ryo-N7** [comment]
@nickdickinson  any updates on the new version for me to test yet? i won't be able to test before our monday meeting at this rate

**Comment by nickdickinson** [comment]
@akbertram Can you help me to get the sorting to work correctly?

1. Is it possible to sort across multiple columns? I tried to add to the list of sorts but it seems to ignore additional sorts... 
2. When column names are pretty columns like the UI and have spaces and special symbol, the sort object seems to work like this:
```
rcrds %>% addSort(list(list(dir = "DESC", field = "Identifier number")))
```
But in the web interface, I see it appending "sort$" to the column name (which happens to be the form field id in the UI. But I cannot use the format "sort$Identifier number" presumably because it has a space in it. I don't think the "sort$[Identifier number]" works either. 

It also does not seem to work with the form field ID if I don't explicitly name the column with the form field ids. 

Is there a reason to add "sort$"?

**Comment by Ryo-N7** [comment]
hey @nickdickinson   

getting some regressions when using the new `columnStyle()` functions to grab the columns exactly as what's in the UI labels:

![colnames-UI-act4 33](https://user-images.githubusercontent.com/19657164/226307998-d3139f0b-1c1a-491b-a6a9-f728617b0d2b.PNG)

![image](https://user-images.githubusercontent.com/19657164/226307922-f288634f-23cd-494c-9ba7-ff04e5dd8d73.png)

compared with the successful implementation from last week/2 weeks ago: 

https://github.com/bedatadriven/activityinfo-R/issues/48#issuecomment-1463939171

**Comment by Ryo-N7** [comment]
the output object from `getRecords()` (as in running that without `collect()`) gives me a list object that gives me weird errors and is also an object that can't be `View()`-ed nor inspected as a usual R object.

I can use `str()` to look at it but it doesn't give me helpful info. So if I want to first explore what columns and rows there are I have to use `collect()` to download the entire thing, for a large form that is a bit of wasted effort/RAM space.

Is there anyway we could use something like `glimpse()` on a `getRecords()` object to look at the schema or get some summary of the data set somehow?

Otherwise I'd have to `collect()` all to inspect or have the form in ActivityInfo open in another window or something

Not quite familiar with the dbplyr object to know how feasible it is or not

**Comment by Ryo-N7** [comment]
yeah, it's fine   >> 
![glimpse-rcrds](https://user-images.githubusercontent.com/19657164/226557755-521b0cea-a050-4f6a-b460-eb44cacca8f6.PNG)


still not sure what the `Error in names[[i]] : subscript out of bounds` error is though

**Comment by Ryo-N7** [comment]
not nearly as familiar with dbplyr but i assume that one would still be able to check out the object following some tidy-steps without running `collect()`? 

below i ran some of the test code, without the `collect()` part and got some grouping error:

![rcrd-tidy-fail](https://user-images.githubusercontent.com/19657164/226558628-33315d7a-a7a6-441d-b17a-4c950cb9041d.PNG)
