### ISSUE TITLE
Add check.names argument to queryTable() to avoid passing column names through make.names

### ISSUE THREAD

**Issue by Ryo-N7** [bedatadriven/activityinfo-R#55]
names don't match via 'Export via R' and the data.frame result, probably because JSON doesn't like spaces and adds the `.`?

![image](https://user-images.githubusercontent.com/19657164/215052513-6122d7fb-f319-49ab-9fcf-c84cf80693a9.png)

of course, i can just use the backticks, ``Cargo del entrevisado`` and I thiiiink that solves the problem (not sure??)  but if I'm just copy-pasting directly from 'Export via R' I will either forget or simply not notice then when I try to 'select' columns I can't find them

**Comment by akbertram** [comment]
An argument for `unique.names`  ?
