### ISSUE TITLE
`getQuantityTable()` messages doesn't update progress %

### ISSUE THREAD

**Issue by Ryo-N7** [bedatadriven/activityinfo-R#56]
![quantab-message-2](https://user-images.githubusercontent.com/19657164/215055062-bb30cea1-fd10-4045-a768-5319375c0758.PNG)
![quantab-message-1](https://user-images.githubusercontent.com/19657164/215055070-1b4189ef-bdcd-4dc4-b808-450d5350a79e.PNG)

**Comment by akbertram** [comment]
Currently, only the import records job provides feedback on progress. We will make a note of this potential improvement in the ActivityInfo backlog.
