### ISSUE TITLE
`getRecordHistory()` output in data.frame format

### ISSUE THREAD

**Issue by Ryo-N7** [bedatadriven/activityinfo-R#57]
fairly simple, see example below:
```
rechist <- getRecordHistory(formId = "c8301e4022c", recordId = "cman42dl4qztru2d")

rechist_df <- tidyr::as_tibble(rechist) %>% 
  tidyr::unnest_wider("entries") %>% 
  tidyr::unnest_wider("user")
```

![gethist-df](https://user-images.githubusercontent.com/19657164/215058986-cce73819-7ce1-491d-b771-4273cdc9b049.PNG)

would like to expand out the 'values' list-field into their own columns but need to account for the fact that the first row when the record is added has a NULL in it compared to the other values for that column

**Comment by nickdickinson** [comment]
Add `as.data.frame()` S3 function

**Comment by Ryo-N7** [comment]
done by me in latest PR for v4.33
