### ISSUE TITLE
Function to retrieve same columns as presented in the user interface

### ISSUE THREAD

**Issue by akbertram** [bedatadriven/activityinfo-R#58]
The user interface uses a specific set of heuristics to produce a flat table from a form with references. In many cases, those using R want to refer to the same set of columns and column names.

We need a way to query this form specifically, perhaps a separate function.

**Comment by Ryo-N7** [comment]
should this be included in the new `getRecords()` as an optional argument? 

tbh i would rather have this quick fix in `queryTable()` first as this issue is more of a immediate need than the big evolutions that we're doing for `getRecords()`

**Comment by nickdickinson** [comment]
Ryo, which quick fix are your referring to for queryTable? #55? Or something else like the reference columns?

**Comment by Ryo-N7** [comment]
this quick fix as in the one labelled in this issue >> have a function that grabs the table, with column names (including references) as exactly as we see it in the User Interface

**Comment by Ryo-N7** [comment]
as shown by @nickdickinson today at our meeting, this is nearly done. just have to take out the `[ ]` and replace `.` with spaces so column names are exactly as the UI

**Comment by nickdickinson** [comment]
So far:
![Image](https://user-images.githubusercontent.com/1900032/221580582-1f56d4e2-eeb8-4fea-8943-35359d3e040d.png)


![Image](https://user-images.githubusercontent.com/1900032/221580748-c7c96f05-ecf1-473f-98ba-1a6741e7b7cd.png)

There is the extra ID column for the reference field. Is that an issue? If so, I'll have to tell it to exclude those fields when getting the table exactly as the UI.

Also, I do not know how to request the record ids in case you would want to know those. It seems those are given as an `@id` column when giving an empty query for the columns but that otherwise that `@id` format does not work to request the record id...

**Comment by Ryo-N7** [comment]
I forgot what you showed me but this does mean i can pass "CSO Name" and other arguments TO `queryTable()` and be able to grab these columns from the API, right?

ex. in form "blah", `Regional ME Staff` is a reference field pointing to the form "Regional ME Staff", the key field is set as `ID`. Therefore, in form "blah" in the UI, it shows up as "Regional ME Staff ID". I need to be able to query for "Regional ME Staff ID" and still get the proper field even though in the API an actual field named "Regional ME Staff ID" doesn't exist (it's just a representation of the "ID" field in "Regional ME Staff" in the UI).

`queryTable(formId = "blah", columns = "Regional ME Staff ID")` (or whatever)

**Comment by nickdickinson** [comment]
In the latest dev version 4.33

`queryTable(form = fmTree)` will give the columns as in my comment above and like the UI with the addition of the reference ID column. No need to specify them.

`queryTable(form = fmTree$root)` with the form ID will provide the API default with the record IDs.

I've created a new helper function `uiColumns(x, select)` help you to select using what you see in the UI:
```
queryTable(form = fmTree, columns = uiColumns(fmTree, select = "When were you born?"))
```

This is a quick workaround. I think the better solution in the long-run is the tidy-select pattern with lazy data frame. Something like:
```
getRecords(form, asUI = TRUE) %>% select() %>% pull()
```

**Comment by Ryo-N7** [comment]
great, thanks I'll get to work then

**Comment by Ryo-N7** [comment]
found a small typo: `Line 321` in `forms.R`

> stopifnot("logicalAs**_SingelSelect_** must be TRUE or FALSE" = is.logical(logicalAsSingleSelect))

**Comment by Ryo-N7** [comment]
i'm getting some errors when i try to use `addForm(0` with the form schema object i created with `formSchemaFromData()`:
```
larlar <- tibble(a = 1:5, b = factor(paste0(1:5, "_stuff")), a_logical_column = 1:5==4, date_col = (seq(as.Date("2021-07-06"),as.Date("2021-07-10"),by = 1)))

larlarschm <- formSchemaFromData(
  x = larlar, 
  databaseId = "c34mde8ldvep9q515", label = "My new form schema!!", 
  keyColumns = "b", 
  logicalAsSingleSelect = FALSE) 

upform_res1 <- addForm(larlarschm$schema)
```

![formupdate](https://user-images.githubusercontent.com/19657164/223451550-06d6da79-5d77-4aa6-83c5-4add1ebd6f43.PNG)

**Comment by nickdickinson** [comment]
Thanks for testing @Ryo-N7. I think I was in a bit of a rush so I'll try this out and add a test or two to  the branch you are on.

**Comment by nickdickinson** [comment]
@Ryo-N7  I've updated branch v4.33 with the fixes to formSchemaFromData() which now has a working test in place. There were a few quirks here and there (for example no support for factors in importTable) but I think I've addressed all I could find. Hopefully you can find some time to try it out again. FYI, I also merged some very basic implementation of getRecords(). Right now it works to look at the table and collect() it. But much of scaffolding is there and we should have a simple version of selecting, slicing and sorting in place. Possibly some filters but still in the activityinfo style.

**Comment by Ryo-N7** [comment]
hey @nickdickinson    getting this error on install:

`Error: object 'tidyselect_data_has_predicates' is not exported by 'namespace:tidyselect'`

![installerr](https://user-images.githubusercontent.com/19657164/223742444-8e8df04e-4fa8-4ff8-bac3-aa47e3a824ad.PNG)

**Comment by nickdickinson** [comment]
That's weird, I cannot replicate it.... maybe try to update tidyselect?

**Comment by Ryo-N7** [comment]
ah great, that did it ... thanks!

**Comment by nickdickinson** [comment]
queryTable now supports `queryTable(columns = prettyColumns())`

**Comment by Ryo-N7** [comment]
hey, i think switching over to the new `columnStyle()` functions sort of muddled things a bit:

this is what the labels look like in the UI for a table i want to grab:
![actual-ui](https://user-images.githubusercontent.com/19657164/226367352-f867710e-ef50-4fb5-a9ea-10efbe06d5a4.PNG)


-------------------

this:
```
  res_all <- getRecords(form = table_id, style = prettyColumnStyle()) %>% 
    collect()
```
gives me this:
 
![res-all](https://user-images.githubusercontent.com/19657164/226366742-7a2479f7-5e91-4679-b1c7-1a140a137ece.PNG)

and this:
```
  res_labels <- getRecords(form = table_id, style = allColumnStyle(columnNames = "label")) %>% 
    collect()
```
gives me this:

![res-labels](https://user-images.githubusercontent.com/19657164/226366789-d43055a8-d28d-4694-809d-45a8b223d404.PNG)

finally, this gives me:
```
  res_ids <- getRecords(form = table_id, style = allColumnStyle(columnNames = "id")) %>% 
    collect()
```
this:
![res-ids](https://user-images.githubusercontent.com/19657164/226366818-a306f095-86e3-459c-9bb6-aab2e2efc6f4.PNG)


2nd one is supposed to be what it should be but the `.` between the words // replacing the blank spaces -- have been added back in so i can't match by the exact UI column name which doesn't have the `.`

unless i need to add that `make.names` argument but that's only in `queryTable()` and i can't find it in the new `getRecords()` + `columnStyle()` functions

**Comment by nickdickinson** [comment]
I will need to create a test case to see what is happening. It looks like `registry_participant `is becoming `participant_name`..... is one the label of the reference table and one the reference field label? 

The second and first one are actually identical just a . has been put in instead of a space I think.

**Comment by Ryo-N7** [comment]
yeah `registry_participant participant_name` and the `DOB` one are both reference fields, coming from the `registry_participant` table. the key fields set are the `participant_name` and `DOB`. 

the label of the field in the form itself is **also** `participant_name` so maybe that's why it's getting confused?

![part-name-lab](https://user-images.githubusercontent.com/19657164/226380635-ed96136a-5bf7-4efe-a430-b99f9d168a3f.PNG)

in the parent form: 
![partname-parent](https://user-images.githubusercontent.com/19657164/226381294-b1ab0c3d-2516-4d78-aa41-a3e079df1442.PNG)
