### ISSUE TITLE
Rename importTable() to importRecords()

### ISSUE THREAD

**Issue by akbertram** [bedatadriven/activityinfo-R#78]
I would like to rename importTable() to importRecords() so that the naming is consistent with the other methods: addRecord(), updateRecord(), etc. 

I can deprecate importTable and keep it as an alias.

What do you think @Ryo-N7 @nickdickinson

**Comment by Ryo-N7** [comment]
yep, I agree! this definitely makes things consistent with the other `_Record()` functions

**Comment by nickdickinson** [comment]
I've created the alias and deprecated importTable(). Also updated NEWS.
