### ISSUE TITLE
BUG: importTable/Records() server error for large data sets (not related to GCP limits #66)

### ISSUE THREAD

**Issue by Ryo-N7** [bedatadriven/activityinfo-R#81]
I know this is `importRecords()` now but I don't think any of the internals have changed. So i've been getting 'server error' problems for extremely large data uploads. This shouldn't be an issue with the GCP stuff in #66 as I'm still able to get a few rows of data uploaded but at various points of the upload progress, I bump into `SERVER_ERROR` 

![gen-able](https://user-images.githubusercontent.com/19657164/227969369-a4d9098f-decb-4e9d-bea9-363131c16172.PNG)

but the response doesn't actually give me any details, just the `executeJob()` job ID + error

![](https://user-images.githubusercontent.com/19657164/225907709-2e317587-4fae-47ac-8c34-e9c7ee387b50.PNG)

> Error in executeJob("importRecords", descriptor = list(formId = formId, :
> Job ahBlfmFjdGl2aXR5aW5mb2V1chALEgNKb2IYgICAnaiviwoM failed. Code: SERVER_ERROR, Message: Server error

![](https://user-images.githubusercontent.com/19657164/227510652-ee4e9da3-1663-4f5b-b4e6-80c0eb2060be.PNG)

is there a way for me to...
1.  access the job error
2. have the R package expose this in more detail in a better way 
3. Or will I continue need to send in a ticket to ActivityInfo for each of these so Alex can look it up from his end?

**Comment by akbertram** [comment]
This is an issue with the ActivityInfo API: https://bedatadriven.atlassian.net/browse/AI-3366
