### ISSUE TITLE
BUG: adding new field (`addFormField()`) with same exact field ID as another field doesn't throw errors // modifying existing fields with schema functions

### ISSUE THREAD

**Issue by Ryo-N7** [bedatadriven/activityinfo-R#82]
as i was trying to test `migrateFieldData()` , i was also thinking about the fact that we don't have a specific function to **modify** existing fields...?

so instead what I tried to do was create "new" fields or more like modifying existing ones by setting the field ID the same as an already existing field with the `addFormField()` functions but this simply creates another field with the SAME ID in the schema.

both fields have ID: `ccwhu70lfrpd3z6e`

![overwrite-field-same-id](https://user-images.githubusercontent.com/19657164/228121631-823dd45d-669e-46bb-a2e0-e95be864c018.PNG)

i can even successfully push that updated form schema to the server
![succs-copy-form](https://user-images.githubusercontent.com/19657164/228121640-19fec138-429c-4e99-a870-7787d2fdb36a.PNG)

it shows up in the UI, and you can grab the fields through the "export" button but the fields show up with the SAME field ID, which "should" theoretically cause problems but it isn't somehow

both fields have ID: `ccwhu70lfrpd3z6e`

![copy-field-ui](https://user-images.githubusercontent.com/19657164/228121757-b1d07426-2e1a-4757-a32f-45e4fc7a5404.PNG)
![same-field-id-ui](https://user-images.githubusercontent.com/19657164/228121765-2353a876-45b5-40f4-9766-f0a1bb5ffa57.PNG)

**Comment by Ryo-N7** [comment]
Also, instead of wrapping the formschema functions with `addFormField()` 

i instead also tried to modify existing fields by simply piping through the `_FieldSchema()` functions to the existing schema but i keep bumping into errors:

![step-newdesc-text](https://user-images.githubusercontent.com/19657164/228127591-2d4b0f90-300a-499c-afd7-bd3372b4258b.PNG)

while there is a "code" argument as in the function docs, it doesn't show up in the auto-complete:

![code-not-pop](https://user-images.githubusercontent.com/19657164/228127948-bbdb9d14-f06e-463c-a741-6ad2377c80f7.png)

same with `key`, `required` and `hideInTable`, and the function keeps throwing an error if you don't include them.

i imagine this is because normally you're supposed to use `addFieldForm()` which automatically fills those in for you?

anyway, once i fill in every single argument manually, i still get another error:

![modify-eixsting](https://user-images.githubusercontent.com/19657164/228128427-83fd9955-2f09-4852-8810-20c1c5b0da82.PNG)

this probably means that I'm not using this properly // we don't have a function to modify existing fields in a form schema?

**Comment by Ryo-N7** [comment]
while `deleteFormField()` allows you to reference the field you want to delete with ANY of `label/code/id` perhaps this shouldn't be the case?

because in cases like above where duplicate fields can be created with the same `label/code/id` that can cause problems?

i was thinking about how any new `modifyField()` function we create, we need to be more specific and have the user supply the `field ID` ? or will that be too restrictive and we should simply do what `deleteFormField()` does currently?

**Comment by Ryo-N7** [comment]
- error if there's more than one match in terms of the `label` 

- addFormField() should replace ID/code that are duplicated by accident by user

- duplicate labels in formulas

- `modifyField()`? t.b.d.... edge cases (id/code duplication?)

- df view >>> mutate() >>> change back into list-format >>> `updateFormSchema()`

**Comment by nickdickinson** [comment]
This should now be addressed including a few more functions:Adding addition form checks to addForm(), updateFormSchema(), and validateFormSchema()
