### ISSUE TITLE
Reserved keywords for ActivityInfo in R package

### ISSUE THREAD

**Issue by nickdickinson** [bedatadriven/activityinfo-R#85]
@akbertram Do we have a list of reserved keywords? It may be good to add this to the sanity check for codes in created fields and schemas.

**Comment by akbertram** [comment]
The only consideration is that codes must match the pattern `^[A-Za-z][A-Za-z0-9_]{0,31}$`

**Comment by nickdickinson** [comment]
Ok thanks!

**Comment by nickdickinson** [comment]
I've added a check for code names when a formField is added to a form schema or when a form schema is being processed in a number of places.
