### ISSUE TITLE
Respect standard interactive() session flag

### ISSUE THREAD

**Issue by akbertram** [bedatadriven/activityinfo-R#86]
@nickdickinson I'm not sure I see the rationale for have a seperate ActivityInfo interactive flag, especially for authentication. If we are running from Rscript or other non-interactive context, we should not be prompting to save tokens.

**Comment by nickdickinson** [comment]
It should be respected. I believe you may be looking at the code required to run tests emulating an interactive session. interactive2() is internal to ensure we can run tests but otherwise, unless you use the undocumented option, it is only there for tests.

**Comment by akbertram** [comment]
Ah ok got it!
