### ISSUE TITLE
Billing account info functions

### ISSUE THREAD

**Issue by Ryo-N7** [bedatadriven/activityinfo-R#97]
Now that billing account info API endpoints are available, need to create the R functions that connects to them so billing users can grab this info

- `getBillingDatabaseUsers()`
- `getBillingDatabases()`
- `getBillingDomains()`
- `getBillingInfo()`
- `getBillingUsers()`
- `getDatabaseOwner()`

**Comment by nickdickinson** [comment]
Hi @Ryo-N7. I've made some updates here for your information in case you are using these function in 4.36:

The `billingId -> billingAccountId` to match the api. Also, I've made adjustments to `getDatabases()` and `getDatabaseTree()` and related billing functions to return character vectors for the billingAccountId as they are int64 and this will be more consistent in R. I've also tried to make the JSON function return character vectors for bigints but not sure if that will work. Overall it should be more consistent. I've also put the `asDataDrame = TRUE` argument to the end of the parameters to match the other package functions. I've also added tests and few columns to each dataframe to include all information. I had to unpack the "owner" column into three columns ("ownerId", "ownerName", "ownerEmail") in `getBillingAccountDatabases()`
